# Generated by Django 5.1.5 on 2025-03-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sortapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
