# Generated by Django 5.1.5 on 2025-02-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(max_length=100)),
                ('stage', models.IntegerField()),
                ('stemail', models.EmailField(max_length=254)),
            ],
        ),
    ]
